# Generated by Django 5.2.6 on 2025-09-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='posts/')),
                ('type_of_post', models.CharField(choices=[('N', 'News'), ('P', 'Photo'), ('V', 'Video')], max_length=5)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
