# Generated by Django 5.2.6 on 2025-11-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type_of_post',
            field=models.CharField(choices=[('N', 'Новини'), ('P', 'Снимка'), ('V', 'Нормална публиация')], max_length=5),
        ),
    ]
